services:
  - type: web
    name: dihhj-backend
    env: node
    plan: free
    rootDir: ./DihhJ Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        value: mongodb+srv://chulbuleMishraJi:Jivanshu1@chulbulemishraji.8mcwh5g.mongodb.net/?retryWrites=true&w=majority&appName=chulbuleMishraJi
      - key: DB_PASSWORD
        value: Jivanshu1
      - key: DATABASE_NAME
        value: dihhj_backend
      - key: CORS_ORIGINS
        value: http://localhost:3000,http://localhost:3001,https://dihhjbitchin-ido5.onrender.com
      - key: BCRYPT_ROUNDS
        value: 12
